### PR TITLE
Fix low priority

### LINKED ISSUE #64: [Tx] Low priority problem
Tx will be low priority because of the `nonce` problem, we should solve it by set it to `-1` when encounter this problem

### PR DESCRIPTION
**Pull request by zikunfan**
Fixed #64

### CODE REVIEW

**Review by yuhui1208 — APPROVED** [review]

**Review by LowEntropyBody — APPROVED** [review]

File: src/services/util.ts [hunk 1]
```diff
@@ -114,6 +118,26 @@ export function sleep(time: number) {
   return new Promise(resolve => setTimeout(resolve, time));
 }
 
+export async function handleSworkTxWithLock(handler: Function) {
+  if (txLocker.swork) {
+    return {
+      status: 'failed',
```
Comment (pangwa) [inline src/services/util.ts:124]: could be more specific, e.g. "failed: sworker locked."

**Review by pangwa — APPROVED** [review]

File: src/services/util.ts (hunk 1 above)
Comment (zikunfan) [reply src/services/util.ts:124]: this is just for outter call judge
